
name: Checks
 
on: [pull_request]
 
env:
  IMAGE_TAG: nest-api
 
jobs:
  test:
    name: Build/Format/Tests
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3
 
      - name: Build the Docker image
        run: docker build -t $IMAGE_TAG --target=create-build .
 
      - name: Run Prettier
        run: docker run $IMAGE_TAG sh -c 'npm run format:verify'
 
      - name: Run ESLint
        run: docker run $IMAGE_TAG sh -c 'npm run lint'
 
      - name: Run tests
        run: docker run $IMAGE_TAG sh -c 'npm run test'